apiVersion: v1
kind: Namespace
metadata:
  name: app-namespace
---
apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
  namespace: app-namespace
type: Opaque
data:
  mongo-user: bW9uZ28=        # 'mongo' base64 encoded
  mongo-password: bW9uZ28=    # 'mongo' base64 encoded
  mongo-database: dmlkZW9fcHJvY2Vzc29y    # 'video_processor' base64 encoded
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: svc-mongo-database
  namespace: app-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: svc-mongo-database
  template:
    metadata:
      labels:
        app: svc-mongo-database
    spec:
      containers:
        - name: svc-mongo-database
          image: mongo:latest
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: mongo-user
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: mongo-password
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: mongo-data
              mountPath: /data/db
      volumes:
        - name: mongo-data
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: svc-mongo-database
  namespace: app-namespace
spec:
  selector:
    app: svc-mongo-database
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
  type: ClusterIP